version: 2.1

orbs:
  android: circleci/android@2.3.0

jobs:
  before_script:
    - touch local.properties

  build:
    executor:
      name: android/android-machine
      resource-class: large
      tag: 2023.07.1
    steps:
      - checkout
      - run: java --version
      - restore_cache:
          key: android-orb-v1-
      - android/change-java-version:
          java-version: 17
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          key: 'android-orb-v1-{{ epoch }}'
          paths:
            - ~/.android/build-cache
            - ~/.android/cache
      - run:
          name: Touch local properties
          command: touch local.properties
      - run: echo "BASE_URL=$BASE_URL" >> ~/repo/local.properties
      - run: echo "BASE_URL_IMAGE=$BASE_URL_IMAGE" >> ~/repo/local.properties
      - run: echo "API_KEY=$API_KEY" >> ~/repo/local.properties
      - run:
          name: Run Build
          command: ./gradlew build
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - store_test_results:
          path: app/build/test-results
      - store_artifacts:
          path: app/build/outputs/apk/debug/
          destination: artifact-file